# Make sure this is before the 'exec' command or it won't be sourced.
[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

export _JAVA_AWT_WM_NONREPARENTING=1

# set baground
WALLPAPERS="$HOME/git/vrkansagara/dwm/images"
while true; do
  find ${WALLPAPERS} -type f -iname "*.jpg" | shuf -n 1 | xargs feh --bg-fill
    sleep  5m
done&

# Laptop/Desktop specific start up
$HOME/.vim/src/Sh/MacBookAir/FunctionKey.sh
$HOME/.vim/src/Sh/System/battery.sh &

### Start up program(s) ###
# st , dwm transperent
/usr/bin/compton &
# ~/Hubstaff/HubstaffClient.bin.x86_64 &
# ~/Applications/workcomposer-linux-installer.AppImage &
# keepassxc &
# ringcentral &
# remmina &
# anydesk &
# ~/Applications/Postman/Postman &
# /usr/local/bin/st -c vrkansagara-ide -n vrkansagara-ide -e vim $HOME/www &
#/usr/local/bin/st -c firle-explorer -n firle-explorer -e ranger $HOME/www &
# skype &
# thunderbird &
# clion &
# phpstorm &

/usr/bin/firefox &
/usr/local/bin/st &
guake &
teams &
slack &

# DWM top bar using conky
while true; do
    (conky | while read LINE; do xsetroot -name "$LINE"; done)
    sleep 1
done&

#evaluate the SSH agent
export GPGKEY=8BA6E7ABD8112B3E
killall gpg-agent ssh-agent

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747465
/usr/lib/notification-daemon/notification-daemon &

# X window lock start ( compile slock if not)
xautolock -time 2 -locker slock &

# zsh/demnu clean cache
mkdir -p $HOME/old
mkdir -p $HOME/tmp
mv .bash* $HOME/old
mv $HOME/.cache/dmenu_run $HOME/old
mv .zcompdump-* $HOME/old

# Start Window Manager (Alwayse last line)
# Log stderror to a file
# Insted of quiting dwm , make it hot reload(Will not disturbe your stream while hot reload)
while true; do
	/usr/local/bin/dwm 2>&1 >> $HOME/tmp/dwm.log
done
